### ISSUE TITLE
Home work ts

### ISSUE THREAD

**Issue by reemaRahhal** [Fullstack-Alfanar/amal-profile#12]
Hi Amal
Out of curiosity I looked at your home work I liked the README file looks interesting.
 I have a comment in the TS file Elias asked not to upload a NODE MODUELES file to the github. To do this you need to create a git ignore file in VS and copy a NODE MODUELS file name inside

**Comment by AmalShalabi** [comment]
Thank You! .gitignore  has been Added.

**Comment by EliasSalom** [comment]
then now you can close this issue!!
